<?php

namespace DBCore\Scoop;

use Scoop\Database\Model;

/**
 * Class Test3
 * @package DBCore\Scoop
 * @author jrobinson (robotically)
 * @date 2016/05/18
 * @property mixed $id
 * @property mixed $name
 * @property mixed $dateTimeAdded
 * AUTO-GENERATED FILE
 * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
 * Put your code in DB\Scoop\Test3
 */
class Test3 extends Model {

    const SCHEMA = 'scoop';
    const TABLE = 'test3';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'dateTimeAdded',
        );

    public static $dBColumnPropertiesArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'name' => 
          array (
          ),
          'dateTimeAdded' => 
          array (
          ),
        );

    protected $dBValuesArray = 
        array (
          'id' => NULL,
          'name' => NULL,
          'dateTimeAdded' => NULL,
        );

}

?>