<?
/**
  * @author jrobinson (robotically)
  * @date 2015/09/25
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DB_Peak_History
  */
class DBCore_Peak_History extends Database_Model {

    const SCHEMA = 'peak10';
    const TABLE = 'history';
    const AUTO_INCREMENT_COLUMN = 'historyID';
    const PRIMARY_KEYS = 
        array (
          0 => 'historyID',
        );

    public $historyID = NULL;
    public $userID = NULL;
    public $columnName = NULL;
    public $old = NULL;
    public $new = NULL;
    public $dateTimeAdded = NULL;
    public $DBColumnsArray = 
        array (
          'historyID' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'userID' => 
          array (
          ),
          'columnName' => 
          array (
          ),
          'old' => 
          array (
          ),
          'new' => 
          array (
          ),
          'dateTimeAdded' => 
          array (
          ),
        );




}

?>