<?
/**
  * @author jrobinson (robotically)
  * @date 2015/10/02
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DB_Peak_UserTypes
  */
class DBCore_Peak_UserTypes extends Database_Model {

    const SCHEMA = 'peak10';
    const TABLE = 'userTypes';
    const AUTO_INCREMENT_COLUMN = 'userTypeID';
    const PRIMARY_KEYS = 
        array (
          0 => 'userTypeID',
        );

    public $userTypeID = NULL;
    public $userType = NULL;
    public $DBColumnsArray = 
        array (
          'userTypeID' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'userType' => 
          array (
          ),
        );




}

?>