<?
/**
  * @author jrobinson (robotically)
  * @date 2015/10/02
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DB_Peak_Phone
  */
class DBCore_Peak_Phone extends Database_Model {

    const SCHEMA = 'peak10';
    const TABLE = 'phone';
    const AUTO_INCREMENT_COLUMN = 'phoneID';
    const PRIMARY_KEYS = 
        array (
          0 => 'phoneID',
        );

    public $phoneID = NULL;
    public $userID = NULL;
    public $phone = NULL;
    public $dateTimeAdded = NULL;
    public $dateTimeUpdated = NULL;
    public $DBColumnsArray = 
        array (
          'phoneID' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'userID' => 
          array (
          ),
          'phone' => 
          array (
          ),
          'dateTimeAdded' => 
          array (
          ),
          'dateTimeUpdated' => 
          array (
          ),
        );




}

?>