<?
/**
  * @author jrobinson (robotically)
  * @date 2015/10/02
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DB_Peak_Addresses
  */
class DBCore_Peak_Addresses extends Database_Model {

    const SCHEMA = 'peak10';
    const TABLE = 'addresses';
    const AUTO_INCREMENT_COLUMN = 'addressID';
    const PRIMARY_KEYS = 
        array (
          0 => 'addressID',
        );

    public $addressID = NULL;
    public $userID = NULL;
    public $street1 = NULL;
    public $street2 = NULL;
    public $city = NULL;
    public $state = NULL;
    public $stateAbbr = NULL;
    public $zip = NULL;
    public $zipPlusFour = NULL;
    public $dateTimeAdded = NULL;
    public $dateTimeUpdated = NULL;
    public $DBColumnsArray = 
        array (
          'addressID' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'userID' => 
          array (
          ),
          'street1' => 
          array (
          ),
          'street2' => 
          array (
          ),
          'city' => 
          array (
          ),
          'state' => 
          array (
          ),
          'stateAbbr' => 
          array (
          ),
          'zip' => 
          array (
          ),
          'zipPlusFour' => 
          array (
          ),
          'dateTimeAdded' => 
          array (
          ),
          'dateTimeUpdated' => 
          array (
          ),
        );




}

?>