<?
/**
  * @author jrobinson (robotically)
  * @date 2015/10/02
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DB_Peak_Users
  */
class DBCore_Peak_Users extends Database_Model {

    const SCHEMA = 'peak10';
    const TABLE = 'users';
    const AUTO_INCREMENT_COLUMN = 'userID';
    const PRIMARY_KEYS = 
        array (
          0 => 'userID',
        );

    public $userID = NULL;
    public $firstName = NULL;
    public $lastName = NULL;
    public $favoriteCity = NULL;
    public $userTypeID = NULL;
    public $employeeID = NULL;
    public $companyName = NULL;
    public $dateTimeAdded = NULL;
    public $dateTimeUpdated = NULL;
    public $DBColumnsArray = 
        array (
          'userID' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'firstName' => 
          array (
          ),
          'lastName' => 
          array (
          ),
          'favoriteCity' => 
          array (
          ),
          'userTypeID' => 
          array (
          ),
          'employeeID' => 
          array (
          ),
          'companyName' => 
          array (
          ),
          'dateTimeAdded' => 
          array (
          ),
          'dateTimeUpdated' => 
          array (
          ),
        );




}

?>