<?php

namespace DBCore\JorPw;

use Scoop\Database\Model;

/**
 * Class Test
 * @package DBCore\JorPw
 * @author jrobinson (robotically)
 * @date 2016/02/15
 * @property mixed $id
 * @property mixed $name
 * @property mixed $dateTimeAdded
 * AUTO-GENERATED FILE
 * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
 * Put your code in DB\JorPw\Test
 */
class Test extends Model {

    const SCHEMA = 'jor.pw';
    const TABLE = 'test';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'dateTimeAdded',
        );
    public static $dBColumnPropertiesArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'name' => 
          array (
          ),
          'dateTimeAdded' => 
          array (
          ),
        );


    protected $dBValuesArray = 
        array (
          'id' => NULL,
          'name' => NULL,
          'dateTimeAdded' => NULL,
        );



}

?>