<?
/**
  * @author jrobinson (robotically)
  * @date 2015/10/02
  * AUTO-GENERATED FILE
  * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
  * Put your code in DB_TestSchema_TestTable
  */
class DBCore_TestSchema_TestTable extends Database_Model {

    const SCHEMA = 'test_schema';
    const TABLE = 'testTable';
    const AUTO_INCREMENT_COLUMN = 'testTableID';
    const PRIMARY_KEYS = 
        array (
          0 => 'testTableID',
        );

    public $testTableID = NULL;
    public $column1 = NULL;
    public $DateTimeAdded = NULL;
    public $DateTimeUpdated = NULL;
    public $DBColumnsArray = 
        array (
          'testTableID' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'column1' => 
          array (
          ),
          'DateTimeAdded' => 
          array (
          ),
          'DateTimeUpdated' => 
          array (
          ),
        );




}

?>